version: '2'

services:
  db:
    container_name: 'GENERATE_DOCKER_PREFIX-db'
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    image: 'mysql:8.0'
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - GENERATE_MYSQL_EXPOSE_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: GENERATE_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: GENERATE_MYSQL_DATABASE
      MYSQL_USER: GENERATE_MYSQL_USER
      MYSQL_PASSWORD: GENERATE_MYSQL_PASSWORD

  # Mailhog:
  mailhog:
    container_name: "GENERATE_DOCKER_PREFIX-mailhog"
    restart: unless-stopped
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - GENERATE_MAILHOG_PORT:8025

  wordpress:
    container_name: 'GENERATE_DOCKER_PREFIX-wp'
    restart: unless-stopped
    depends_on:
      - db
    image: 'wordpress:php7.4'
    ports:
      - GENERATE_WEB_PORT:80
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
    volumes:
      - "./wordpress:/var/www/html"
      - "./themes:/var/www/html/wp-content/themes"
      - "./plugins:/var/www/html/wp-content/plugins"
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

networks:
  default:
    driver: bridge
